# -*- coding: utf-8 -*-
"""convertPics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ozdoaqw3-QKT_u0zR0aygt8l3VPPoioR
"""

from skimage import data_dir,io,transform,color

import numpy as np

def convert_gray(f,**args):

     rgb=io.imread(f)   

     gray=color.rgb2gray(rgb)     

     dst=transform.resize(gray,(48,48))       

     return dst

from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)
root_dir = "/content/gdrive/My Drive/"
base_dir = root_dir + 'CMPE258/team_project/'

data_path1=base_dir+'/data/Embarrassed_selected/femaleEmbarrassed/*.jpg'

data_path1

coll = io.ImageCollection(data_path1,load_func=convert_gray)

len(coll)

data_gray_path=base_dir+'data/Embarrassed_selected/gray_embarrassed/gray_embarrassed'

for i in range(len(coll)):
    io.imsave(data_gray_path+np.str(i)+'.jpg',coll[i])

data_path2=base_dir+'/data/Embarrassed_selected/male_embarrassed/*.jpg'
coll2 = io.ImageCollection(data_path2,load_func=convert_gray)

data_gray_path2=base_dir+'data/Embarrassed_selected/gray_embarrassed/gray_embarrassed_m'

for i in range(len(coll2)):
    io.imsave(data_gray_path2+np.str(i)+'.jpg',coll2[i])